name = "discord-oidc"
main = "dist/worker.js"
compatibility_date = "2022-12-24"


[build]
command = "yarn compile"
cwd = "."
watch_dir = "dist/worker.js"


#kv_namespaces = [
#  { binding = "KV", id = "0b9abda82acf461c8d4ecda656217e20", preview_id = "b43c22430b5240dea89cd6cc350d3946" }
#]